// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Serato.Net.Api.Shared;

namespace Serato.Net.Api.Shared.Migrations
{
    [DbContext(typeof(SeratoContext))]
    partial class SeratoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Serato.Net.Api.Shared.Models.TrackInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TrackInfos");
                });

            modelBuilder.Entity("Serato.Net.Api.Shared.Models.TrackInfoEntity", b =>
                {
                    b.OwnsOne("Serato.Net.Structs.TrackInfo", "TrackInfo", b1 =>
                        {
                            b1.Property<Guid>("TrackInfoEntityId")
                                .HasColumnType("uuid");

                            b1.HasKey("TrackInfoEntityId");

                            b1.ToTable("TrackInfos");

                            b1.WithOwner()
                                .HasForeignKey("TrackInfoEntityId");
                        });

                    b.Navigation("TrackInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
